### ISSUE TITLE
Lock down replication factor after cluster has been created

### ISSUE THREAD

**Issue by purplefox** [cashapp/pranadb#360]
We should prevent user from changing replication factor after cluster has been created. We can do this in a similar way to how we do with number of shards - i.e. storing the number in the database itself.

**Comment by mohsalsaleem** [comment]
Hello @purplefox, are you referring to [this](https://github.com/cashapp/pranadb/blob/240847ab89b96f9644ca8e8d3e1b52e13cf7e529/cluster/dragon/dragon.go#L896) shards check implementation?

**Comment by purplefox** [comment]
Yes a similar check
