### ISSUE TITLE
Bug in decimal index cols

### ISSUE THREAD

**Issue by purplefox** [cashapp/pranadb#410]
@alex-cash to fill in the details :)

**Comment by alex-cash** [comment]
When testing a 3-col index where one of the cols was a decimal data type, I noticed that the value being read was the negative of what was in the underlying table. Need to investigate if the value is being written to index entry wrong, or read wrong.

**Comment by purplefox** [comment]
Could you add a failing test which demonstrates the issue?

**Comment by alex-cash** [comment]
Fixed by #416
