### ISSUE TITLE
Sources with uppercase letters in their name can't be queried

### ISSUE THREAD

**Issue by severb** [cashapp/pranadb#446]
Steps to reproduce:

1. Create a source with uppercase letters in its name
2. Query the source
3. _failed to execute statement PDB0002 - Table `test.XVlBzgbaiC` doesn't exist_

The source seems to be created correctly but when querying the table name is lowercased and doesn't match the source name.

**Comment by purplefox** [comment]
Coincidentally I was working on case sensitivity yesterday. Can you check if this is fixed by https://github.com/cashapp/pranadb/pull/448 ?

**Comment by purplefox** [comment]
I'm going to close it, as I believe it's already fixed.
